name: Go Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -cover -v ./...
